- name: The Prometheus Node Exporter role
  hosts: all
  become: yes
  become_method: sudo

  vars:
    prometheus_node_exporter_enabled_collectors:
      - logind
    prometheus_node_exporter_disabled_collectors:
      - netstat

  roles:
    - ansible-role-prometheus-node-exporter

  tags:
    - node-exporter
  


