# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: remove cfg files
  block:

  - name: check if cfg files are present
    stat:
      path: "{{ __cfg.dest }}"
    loop: "{{ __normalized_cfgs.data }}"
    loop_control:
      loop_var: __cfg
      label: "{{ __cfg.dest }}"
    register: __cfg_files

  - name: cfg files are replaced
    copy:
      dest: "{{ __cfg.dest }}"
      content: '# removed file by ansible'
      mode: "{{ httpd_cfg_mode }}"
      backup: true
    loop: "{{ __normalized_cfgs.data }}"
    loop_control:
      loop_var: __cfg
      label: "{{ __cfg.dest }}"
      index_var: __i
    when:
    - __cfg.dest != httpd_main_cfg
    - httpd_conf_d_wr is not defined
    # only if file exists, i.e. don't create it
    - __cfg_files.results[__i].stat.exists

  - name: cfg files are absent
    file:
      path: "{{ httpd_conf_d }}/{{ __cfg.dest|basename }}"
      state: absent
    loop: "{{ __normalized_cfgs.data }}"
    loop_control:
      loop_var: __cfg
      label: "{{ httpd_conf_d }}/{{ __cfg.dest|basename }}"
    when:
    - __cfg.dest != httpd_main_cfg
    notify: reload httpd

  when: httpd_cfgs is defined or cfgs is defined

...
