---
- name: upstart service
  become: true
  template:
    src: "haproxy_exporter.upstart.j2"
    dest: "/etc/init/haproxy_exporter.conf"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - restart haproxy_exporter
