---
# tasks file for cadvisor

- name: cadvisor | create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /opt/cadvisor

- name: cadvisor | download
  become: true
  get_url:
    url: "{{ cadvisor_download }}"
    checksum: "sha256:{{ cadvisor_checksum }}"
    dest: "/opt/cadvisor/cadvisor-{{ cadvisor_version }}"
    force: false
    mode: u=rwx,g=rx,o=rx
  when: cadvisor_binary_local_dir | length == 0

- name: cadvisor | propagate locally distributed cadvisor binary
  copy:
    src: "{{ cadvisor_binary_local_dir }}/cadvisor-{{ cadvisor_version }}"
    dest: "/opt/cadvisor/cadvisor-{{ cadvisor_version }}"
    mode: 0755
    owner: root
    group: root
  when: cadvisor_binary_local_dir | length > 0
  notify:
    - restart cadvisor

- name: cadvisor | symlink
  become: true
  file:
    src: "/opt/cadvisor/cadvisor-{{ cadvisor_version }}"
    path: /opt/cadvisor/cadvisor
    force: true
    state: link

- name: cadvisor | server systemd service
  become: true
  template:
    dest: /etc/systemd/system/cadvisor.service
    src: systemd-system-cadvisor-service.j2
    mode: 0644
  notify:
    - restart cadvisor

- name: cadvisor | enable and start server systemd
  become: true
  systemd:
    enabled: true
    name: cadvisor.service
    state: started
    daemon_reload: true
