# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: converge apache
  hosts: all,!infrastructure_group
  roles:
  - role: mafalb.apache.httpd
    httpd_different_vhosts_d: conf.vhosts.d
    httpd_cfgs:
    - src: httpd.conf.j2
      dest: _main_config
    - src: bla.conf.j2
      dest: test.conf
  tasks:
  - name: index.html is present
    copy:
      content: "{{ ansible_host }}"
      dest: "/var/www/html/index.html"
      mode: '644'

...
