- name: install
  ansible.builtin.package:
    name:
      - haproxy
    state: present
- name: global config template
  ansible.builtin.template:
    dest: /etc/haproxy/global.cfg
    src: 'global.cfg.j2'
    mode: 0644
  notify: restart haproxy
- name: change config file
  ansible.builtin.blockinfile:
    path: /etc/default/haproxy
    block: CONFIG="/etc/haproxy/"
  notify: restart haproxy
