# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: converge apache
  hosts: all,!infrastructure_group

  roles:

  # apache won't be running afterwards
  - role: mafalb.apache.httpd
    httpd_service_managed: false
    httpd_service_enabled: true

  tasks:

  - name: index.html is present
    copy:
      content: "{{ ansible_host }}"
      dest: "/var/www/html/index.html"
      mode: '644'

...
