# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

httpd_container_sections:
- directory
- directorymatch
- files
- filesmatch
- if
- ifDefine
- ifmodule
- ifversion
- location
- locationmatch
- mdomainset
- proxy
- proxymatch
- virtualhost

httpd_default_config:
  ServerRoot: '"{{ httpd_basedir }}"'
  Listen: 80
  IncludeOptional: "{{ httpd_modules_d }}/*.load"
  'Include modules': "{{ httpd_modules_d }}/*.conf"
  User: "{{ httpd_user }}"
  Group: "{{ httpd_user }}"
  ServerAdmin: root@localhost
  ServerName: "{{ ansible_fqdn }}"
  DocumentRoot: '"{{ httpd_documentroot }}"'
  PidFile: "{{ httpd_pidfile }}"
  EnableSendfile: 'on'
  AddDefaultCharset: UTF-8

  ErrorLog: "{{ httpd_logdir }}/error_log"
  LogLevel: warn

  'IfModule log_config_module':
    _IfModule: log_config_module
    LogFormat:
    - '"%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined'
    - '"%h %l %u %t \"%r\" %>s %b" common'
    'IfModule logio_module':
      _IfModule: logio_module
      LogFormat: '"%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio'
    CustomLog: '"{{ httpd_logdir }}/access_log" combined'

  'IfModule mime_module':
    _IfModule: mime_module
    TypesConfig: /etc/mime.types
    AddType:
    - application/x-compress .Z
    - application/x-gzip .gz .tgz

  'IfModule mime_magic_module':
    _IfModule: mime_magic_module
    MIMEMagicFile: conf/magic

  'Directory /':
    _Directory: /
    AllowOverride: None
    Require: all denied

  'Directory document_root_parent':
    _Directory: "{{ httpd_documentroot|dirname }}"
    AllowOverride: None
    Require: all granted

  'Directory documentroot':
    _Directory: "{{ httpd_documentroot }}"
    Options: Indexes FollowSymlinks
    AllowOverride: None
    Require: all granted

  'IfModule dir_module':
    _IfModule: dir_module
    DirectoryIndex: index.html

  'Files .ht*':
    _Files: .ht*
    Require: all denied

  'Include config': "{{ httpd_conf_d }}/*.conf"

...
