---
- hosts: all
  post_tasks:
    - name: copy apache passwd sample
      copy:
        src: files/sample/apachepasswd
        dest: /etc/apache2/conf/apachepasswd
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
    - name: install apache utils for htpasswd
      apt:
        package: apache2-utils
  roles:
    - apache_httpd
    - prometheus_apache_exporter_role
